name: CI/CD: Build and Push to Google Artifact Registry

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}
      REGION: europe-west1
      PROJECT_ID: stocks-455113
      REPO: stocks-analytics-repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker to use GAR
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build Airflow services
        run: |
          docker compose -f Docker/airflow/docker-compose.yaml build

      - name: Tag and push images to GAR
        run: |
          export REGION=${{ env.REGION }}
          export PROJECT_ID=${{ env.PROJECT_ID }}
          export REPO=${{ env.REPO }}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          SERVICES=("airflow-scheduler" "airflow-webserver" "airflow-triggerer" "airflow-worker")
          for SERVICE in "${SERVICES[@]}"; do
            LOCAL_IMAGE="airflow-${SERVICE}"
            REMOTE_IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$LOCAL_IMAGE"

            docker tag ${LOCAL_IMAGE} ${REMOTE_IMAGE}:${IMAGE_TAG}
            docker tag ${LOCAL_IMAGE} ${REMOTE_IMAGE}:latest

            docker push ${REMOTE_IMAGE}:${IMAGE_TAG}
            docker push ${REMOTE_IMAGE}:latest
          done